name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Sync to /var/www/api
        run: |
          sudo rsync -a --delete \
          --exclude '.git' \
          --exclude 'node_modules' \
          --exclude 'vendor' \
          --exclude 'storage' \
          --exclude '.env' \
          --chown ubuntu:www-data \
          "$GITHUB_WORKSPACE/" /var/www/api
      - name: Install deps and reload
        run: |
          cd /var/www/api
          composer install --no-dev -o
          sudo systemctl reload nginx
      - name: Ensure writable dirs
        run: |
          sudo chmod -R 2775 /var/www/api/bootstrap/cache /var/www/api/storage