name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to local filesystem
        run: |
          cd /var/www/api
          git fetch origin
          git reset --hard origin/main   
          sudo composer install --no-dev --optimize-autoloader
  
