name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print runner public IP
        run: |
          echo "🌍 Public IP:"
          curl https://api.ipify.org

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        run: |
          set -e  # Fail fast on error
      
          echo "🔧 Creating .ssh directory..."
          mkdir -p ~/.ssh
      
          echo "🔑 Decoding private key..."
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa || { echo "❌ SSH key decode failed"; exit 1; }
      
          echo "🔐 Setting permissions..."
          chmod 600 ~/.ssh/id_rsa || { echo "❌ chmod failed"; exit 1; }
      
          echo "🔎 Scanning EC2 host key..."
          ssh-keyscan -T 5 -t rsa ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || { echo "❌ ssh-keyscan failed"; exit 1; }
      
          echo "✅ SSH setup complete."


      - name: Deploy via SSH
        run : |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/api
            sudo git pull origin main
          EOF
          
